name:               "Ink"
description:        "A minimalistic jekyll theme for humans"

url:                "http://thinker3197.github.io/Ink"
author:             "thinker3197"
email:              "jhondoe@abc.com"
gravatar_hash:      "de5c7e08016aeaa80d78eacbc33d60cc"
twitter:            "jhondoe"
email:              "jhondoe@abc.com"
github:             "jhondoe"
pinterest:          "jhondoe"
linkedin:           "jhondoe"
facebook:           "jhondoe"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate