name:               "Ink"
description:        "A minimalistic jekyll theme for humans"

url:                ""
author:             "thinker3197"
twitter:
  username:         "jhondoe"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"