name:               "Hao Li"
description:        "Research Associate "

url:                ""
author:             "Hao Li"
email:              "hao.li@uni-heidelberg.de"
twitter:            "bobleegogogo"
github:             "bobleegogogo"
linkedin:           "hao-li-340868154"
researchgate:       "Hao_Li217"


disqus_shortname:   "Hao"

background:         "/papers.co-vd21-black-sea-texture-40-wallpaper.jpg"
#"http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown
    
nav:
  - name:           "Home"
    href:           "/home"
  - name:           "About Me"
    href:           "/aboutme"
  - name:           "Career"
    href:           "/career"
  - name:           "Publications"
    href:           "/publications"
  - name:           "Contact"
    href:           "/contact"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate

highlighter: rouge
